from .bhop import BhopCog
from .admin import AdminCog
from .fetish import FetishCog
from .gladiators import GladiatorsCog
from .imggen import ImageGenCog
from .lastfm import LastFmCog
from .misc import MiscCog
from .spelling import SpellingCog
from .stats import StatsCog
from .urban_dictionary import UrbanDictionaryCog
from .weather import WeatherCog
